# Generated by Django 5.1.3 on 2024-11-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catuser",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
