# Generated by Django 5.1.3 on 2024-11-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_network", "0003_alter_catuser_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catuser",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
