# Generated by Django 5.1.3 on 2024-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cat_network", "0004_alter_catuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catuser",
            name="breed",
            field=models.CharField(
                choices=[
                    ("Abyssinian", "Abyssinian"),
                    ("American Bobtail", "American Bobtail"),
                    ("American Curl", "American Curl"),
                    ("American Wirehair", "American Wirehair"),
                    ("Aphrodite Giant", "Aphrodite Giant"),
                    ("Arabian Mau", "Arabian Mau"),
                    ("Asian Semi-longhair", "Asian Semi-longhair"),
                    ("Australian Mist", "Australian Mist"),
                    ("Balinese", "Balinese"),
                    ("Bambino", "Bambino"),
                    ("Bengal", "Bengal"),
                    ("Birman", "Birman"),
                    ("Bombay", "Bombay"),
                    ("British Shorthair", "British Shorthair"),
                    ("Burmese", "Burmese"),
                    ("Chantilly-Tiffany", "Chantilly-Tiffany"),
                    ("Colorpoint Longhair", "Colorpoint Longhair"),
                    ("Colorpoint Persian", "Colorpoint Persian"),
                    ("Colorpoint Shorthair", "Colorpoint Shorthair"),
                    ("Devon Rex", "Devon Rex"),
                    ("Don Sphynx", "Don Sphynx"),
                    ("Egyptian Mau", "Egyptian Mau"),
                    ("Foldex", "Foldex"),
                    ("German Rex", "German Rex"),
                    ("Havana Brown", "Havana Brown"),
                    ("Khao Manee", "Khao Manee"),
                    ("Korat", "Korat"),
                    ("Maine Coon", "Maine Coon"),
                    ("Minskin", "Minskin"),
                    ("Munchkin", "Munchkin"),
                    ("Oriental", "Oriental"),
                    ("Persian", "Persian"),
                    ("Siamese", "Siamese"),
                    ("Sphynx", "Sphynx"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=50,
            ),
        ),
    ]
